theme: jekyll-theme-minimal
title: lynn dong
description: >
  about me
  - â˜ï¸  cloud engineer
  - ğŸ‚ snowboarding enthusiast
  - ğŸ carb addict
  - ğŸ˜ amateur real estate investor
  - ğŸ’ƒğŸ» dancer
  - ğŸ’© sensitive striver
  - ğŸ‘¾ ex-gamer with semi-annual relapses
  - â˜•ï¸ fueled by caffeine
